kumuluzee:
  name: test-yaml
  server:
    http:
      port: 9094
  version: 1.0
  env:
    name: dev

lpc:
  connections:
    - name: NATS-conn
      type: NATS
      host: nats://localhost
      port: 4222
    - name: Modbus-client
      type: Modbus
      device: /dev/ttya
      baud-rate: 9600
      data-bits: 8
  transformations:
    - name: Transformation to IEEE2030.5 Event in XML format
      description: Transformation that maps from custom event in Modbus to IEEE2030.5 Event structure in XML format
      connections:
        incoming:
          - Modbus-client
        outgoing:
          - NATS-conn
        modbus-function-code: 3
        modbus-device-id: 1
      server-topic: device2.event
      device-format: Modbus
      server-format: JSON
      to-server:
        '{
                   "creationTime": $timestamp,
                   "EventStatus": {
                     "currentStatus": {
                       "lpc:mapping": {
                         "path": 31000,
                         "type": "float",
                         "multiplyer":
                       }
                     },
                     "dateTime": {
                       "lpc:mapping": {
                         "path": 42000,
                         "type": "datetime",
                         "pattern": "dd-MM-yyyy HH:mm:ss"
                       }
                     },
                     "potentiallySuperseded": null
                   },
                   "interval": {
                     "duration": null,
                     "start": null
                   }
                 }'
      to-device:
        modbus-registers:
          - register-address: 31000
            path: /EventStatus/currentStatus
            type: integer
          - register-address: 42000
            path: /interval/start
            type: integer

