kumuluzee:
  name: test-yaml
  server:
    http:
      port: 9094
  version: 1.0
  env:
    name: dev

lpc:
  connections:
    - name: NATS-connection
      type: NATS
      host: nats://localhost
      port: 4222
      reconnect: true
    - name: MQTT-connection
      type: MQTT
      ssl:
        default: true
      host: 37aad5450fca492297d7d3bc3329f4ba.s2.eu.hivemq.cloud
      port: 8883
      username: lpc-user
      password: zv.NaiixwWZ7wCC
  transformations:
    - name: XML IncomingEvent to JSON IEEE2030.5 Event
      description: Example showing transformation of messages from XML to JSON
      connections:
        incoming-connection:
          - MQTT-connection
        incoming-topic: topic1
        incoming-format: XML
        outgoing-connection:
          - NATS-connection
        outgoing-topic: event/myevent
        outgoing-format: JSON
      to-outgoing:
        '{
            "creationTime": $timestamp,
            "EventStatus": {
                "currentStatus": {
                  "lpc:mapping": {
                    "path": "/IncomingEvent/status",
                    "type": "integer",
                    "values": ["scheduled", "active", "cancelled", "cancelled_with_r", "superseded"]
                  }
                },
                "dateTime": {
                  "lpc:mapping": {
                    "path": "/IncomingEvent/datetime",
                    "type": "datetime",
                    "pattern": "dd-MM-yyyy HH:mm:ss"
                  }
                },
                "potentiallySuperseded": false
              },
              "interval": {
                "duration": {
                  "lpc:mapping": {
                    "path": "/IncomingEvent/duration",
                    "type": "integer"
                  }
                },
                "start": {
                  "lpc:mapping": {
                    "path": "/IncomingEvent/start",
                    "type": "date",
                    "pattern": "dd-MM-yyyy"
                  }
                }
              }
            }
        '