kumuluzee:
  name: test-yaml
  server:
    http:
      port: 9094
  version: 1.0
  env:
    name: dev

lpc:
  connections:
    - name: NATS-conn
      type: NATS
      host: nats://localhost
      port: 4222
    - name: MQTT-broker
      type: MQTT
      version: 5
      ssl:
        default: true
      host: 37aad5450fca492297d7d3bc3329f4ba.s2.eu.hivemq.cloud
      port: 8883
      username: lpc-user
      password: zv.NaiixwWZ7wCC
  transformations:
    - name: Transformation to IEEE2030.5 Event in XML format
      description: Transformation that maps from custom event to IEEE2030.5 Event structure in XML format
      connections:
        incoming:
          - MQTT-broker
        outgoing:
          - NATS-conn
      device-topic: device2.event
      server-topic: device2.event
      device-format: JSON
      server-format: XML
      to-server:
        '<event> 
          <creationtime>$timestamp</creationtime> 
          <eventstatus>
            <currentstatus>
              <mapping>
                <path type="integer">/customevent/status</path>
                <values>["scheduled", "active", "cancelled", "cancelled_with_r", "superseded"]</values>
              </mapping>
            </currentstatus>
            <datetime>
              <mapping>
                <path type="datetime">/customevent/datetime</path>
                <pattern>dd-MM-yyyy HH:mm:ss</pattern>
              </mapping>
            </datetime>
            <potentiallysuperseded></potentiallysuperseded>
          </eventstatus>
          <interval> 
            <duration>
              <mapping>
                <path type="integer">/customevent/duration</path>
              </mapping>
            </duration>
            <start>
              <mapping>
                <path type="date">/customevent/start</path>
                <pattern>dd-MM-yyyy</pattern>
              </mapping>
            </start>
          </interval>
        </event>'
      to-device:
        '<customevent>
          <date>
          <mapping>
          <path type="datetime">/event/eventstatus/datetime</path>
          <pattern>dd-MM-yyyy HH:mm:ss</pattern>
          </mapping>
          </date>
          <status>
          <mapping>
          <path type="integer">/event/eventstatus/currentstatus</path>
          <values>["scheduled", "active", "cancelled", "cancelled_with_r", "superseded"]</values>
          </mapping>
          </status>
          <start>
          <mapping>
          <path type="date">/event/interval/start</path>
          <pattern>dd-MM-yyyy</pattern>
          </mapping>
          </start>
          <duration>
          <mapping>
          <path type="integer">/event/interval/duration</path>
          </mapping>
          </duration>
          </customevent>'