kumuluzee:
  name: legacy-protocol-converter
  server:
    http:
      port: 9094
  version: 1.0.1
  env:
    name: prod
  cors-filter:
    servlet:
      enabled: true
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, HEAD, OPTIONS, DELETE"