kumuluzee:
  name: test-yaml
  server:
    http:
      port: 9094
  version: 1.0
  env:
    name: dev

lpc:
  connections:
    - name: NATS-conn
      type: NATS
      host: nats://localhost
      port: 4222
      reconnect: true
    - name: MQTT-broker
      type: MQTT
      version: 5
      ssl:
        default: true
      host: 37aad5450fca492297d7d3bc3329f4ba.s2.eu.hivemq.cloud
      port: 8883
      username: lpc-user
      password: zv.NaiixwWZ7wCC
  transformations:
    - name: Transformation to IEEE2030.5 Event in XML format
      description: Transformation that maps from custom event to IEEE2030.5 Event structure in XML format
      connections:
        incoming-connection:
          - MQTT-broker
        incoming-topic: device2.event
        incoming-format: JSON
        outgoing-connection:
          - NATS-conn
        outgoing-topic: device2.event
        outgoing-format: XML
      validate-schema: true
      to-server:
        element-name: event
        schema-location: https://.../event.xsd
        mapping: '<event> 
          <creationtime>$timestamp</creationtime> 
          <eventstatus>
            <currentstatus>
              <lpc:mapping>
                <path type="integer">/status</path>
                <values>["scheduled", "active", "cancelled", "cancelled_with_r", "superseded"]</values>
              </lpc:mapping>
            </currentstatus>
            <datetime>
              <lpc:mapping>
                <path type="datetime">datetime</path>
                <pattern>dd-MM-yyyy HH:mm:ss</pattern>
              </lpc:mapping>
            </datetime>
            <potentiallysuperseded></potentiallysuperseded>
          </eventstatus>
          <interval> 
            <duration>
              <lpc:mapping>
                <path type="integer">duration</path>
              </lpc:mapping>
            </duration>
            <start>
              <lpc:mapping>
                <path type="date">/start</path>
                <pattern>dd-MM-yyyy</pattern>
              </lpc:mapping>
            </start>
          </interval>
        </event>'
    - name: Transformation to IEEE2030.5 Event in XML format
      description: Transformation that maps from custom event to IEEE2030.5 Event structure in XML format
      connections:
        incoming-connection:
          - MQTT-broker
        incoming-topic: device2.event
        incoming-format: XML
        outgoing-connection:
          - NATS-conn
        outgoing-topic: device2.event
        outgoing-format: XML
      validate-schema: true
      to-outgoing:
        '<event> 
          <creationtime>$timestamp</creationtime> 
          <eventstatus>
            <currentstatus>
              <lpc:mapping>
                <path type="integer">/status</path>
                <values>["scheduled", "active", "cancelled", "cancelled_with_r", "superseded"]</values>
              </lpc:mapping>
            </currentstatus>
            <datetime>
              <lpc:mapping>
                <path type="datetime">datetime</path>
                <pattern>dd-MM-yyyy HH:mm:ss</pattern>
              </lpc:mapping>
            </datetime>
            <potentiallysuperseded></potentiallysuperseded>
          </eventstatus>
          <interval> 
            <duration>
              <lpc:mapping>
                <path type="integer">duration</path>
              </lpc:mapping>
            </duration>
            <start>
              <lpc:mapping>
                <path type="date">/start</path>
                <pattern>dd-MM-yyyy</pattern>
              </lpc:mapping>
            </start>
          </interval>
        </event>'