kumuluzee:
  name: test-yaml
  server:
    http:
      port: 9094
  version: 1.0
  env:
    name: dev

lpc:
  connections:
    - name: NATS-conn
      type: NATS
      host: nats://localhost
      port: 4222
    - name: MQTT-broker
      type: MQTT
      version: 5
      ssl:
        default: true
      host: 37aad5450fca492297d7d3bc3329f4ba.s2.eu.hivemq.cloud
      port: 8883
      username: lpc-user
      password: zv.NaiixwWZ7wCC
  transformations:
    - name: Transformation to IEEE2030.5 Event in JSON format
      description: Transformation that maps from custom event to IEEE2030.5 Event structure in JSON format
      connections:
        incoming:
          - MQTT-broker
        outgoing:
          - NATS-conn
      device-topic: device2.event
      server-topic: device2.event
      device-format: JSON
      server-format: JSON
      to-server:
        '{
                   "creationTime": $timestamp,
                   "EventStatus": {
                     "currentStatus": {
                       "lpc:mapping": {
                         "path": "/customevent/status",
                         "type": "integer",
                         "values": ["scheduled", "active", "cancelled", "cancelled_with_r", "superseded"]
                       }
                     },
                     "dateTime": {
                       "lpc:mapping": {
                         "path": "/customevent/datetime",
                         "type": "datetime",
                         "pattern": "dd-MM-yyyy HH:mm:ss"
                       }
                     },
                     "potentiallySuperseded": null
                   },
                   "interval": {
                     "duration": {
                       "lpc:mapping": {
                         "path": "/customevent/duration",
                         "type": "integer"
                       }
                     },
                     "start": {
                       "lpc:mapping": {
                         "path": "/customevent/start",
                         "type": "date",
                         "pattern": "dd-MM-yyyy"
                       }
                     }
                   }
                 }'

